### ISSUE TITLE
Updated analysis: Create command line arguments for oncoKB token

### ISSUE THREAD

**Issue by jharenza** [d3b-center/PBTA-ALT-analysis#59]
#### What analysis module should be updated and why?
`09-lollipop` - currently, `01-create-lollipop.Rmd` uses R params to call the oncokB token, and this cannot be run in docker as-is. 

#### What changes need to be made? Please provide enough detail for another participant to make the update.
We should create a shell script to take in this token via command line. Perhaps the best way to do this is to convert lines 94-107 to shell and and break up the R notebook into two scripts, one to create the subset maf and one to create the lollipops post oncoKB annotation.

#### What input data should be used? Which data were used in the version being updated?
MAF, histologies file

#### When do you expect the revised analysis will be completed?
This week

#### Who will complete the updated analysis?
@rjcorb can you possibly work on this?

**Comment by rjcorb** [comment]
@jharenza yes, I will get started on this and let you know if I have questions

**Comment by jharenza** [comment]
completed in #62
